### ISSUE TITLE
Website Checklist before Release

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-archive#52]
# Website checklist

## Community
- [ ] Add additional content and projects

## Homepage
- [ ] ...

## Reference Page
- [ ] CVAE()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] DCGAN()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] pitchDetection()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] pix2pix()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] poseNet()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] SketchRNN()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] styleTransfer()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] UNET()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] word2vec()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] example()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] YOLO()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] CharRNN()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] featureExtractor()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] KNNClassifier()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date
- [ ] imageClassifier()
    - [ ] documentation is up-to-date
    - [ ] examples are up-to-date

## Getting Started
- [ ] Getting Started
- [ ] Image Classification
- [ ] Overview
- [ ] Promises and Callbacks
- [ ] Creating your data
- [ ] Preparing your own data
- [ ] Types of Data
- [ ] Data Collection

**Comment by WenheLI** [comment]
For the documentation, should we use ``jsdocs``/inline documentation? Or, we just write them into a separate markdown file?

**Comment by joeyklee** [comment]
@WenheLI - Great question. Ideally I would like to start doing jsdocs/inline documentation. Since we have all of the documentation now on the website (e.g. https://ml5-website-2.netlify.com/reference/api-CVAE/) it shouldn't be too much effort to copy these all over to the `ml5-library`. 

How does this sound for now?
1. Let's add all of the current documentation from the website as in-line comments in `ml5-library` `development` branch.
2. Once we have our next release we can figure out the best methods for generating our documentation and integrating it with our website, examples, etc. 

Do you have time to do a first pass on this @WenheLI ?

**Comment by joeyklee** [comment]
@WenheLI - I will start adding docs in here: https://github.com/ml5js/ml5-library/tree/adds-inline-docs  
Thanks!! 

We should standardize our methods, maybe pulling inspiration from p5? https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js

**Comment by WenheLI** [comment]
@joeyklee - Sure, I can add the docs later! I will follow the documentation on the website for now.

> Once we have our next release we can figure out the best methods for generating our documentation and integrating it with our website, examples, etc.

For this, I think a script or a webpack script might be a good way?

**Comment by joeyklee** [comment]
@WenheLI - Super. I will also do a first pass on documentation right now. 
+ yes, webpack would be the way to go. I think we can use this plug-in to help us: https://www.npmjs.com/package/jsdoc-webpack-plugin

**Comment by joeyklee** [comment]
Something like this?

```javascript
class ImageClassifier {
  /**
   * Create an ImageClassifier.
   * @param {modelName} modelName - The name of the model to use. Current options are: 'mobilenet', 'darknet', and 'darknet-tiny'.
   * @param {HTMLVideoElement} video - An HTMLVideoElement.
   * @param {object} options - An object with options.
   * @param {function} callback - A callback to be called when the model is ready.
   */
  constructor(modelName, video, options, callback) {
    this.modelName = modelName;
    this.video = video;
    this.model = null;
    switch (this.modelName) {
```

**Comment by bomanimc** [comment]
We're live! Closing this for now as further work will likely be expanded into separate issues.
